type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Resume @table {
  user: User!
  fileName: String!
  uploadDate: Timestamp!
  documentUrl: String!
  resumeText: String
}

type AnalysisReport @table {
  resume: Resume!
  analysisDate: Timestamp!
  atsCompatibilityScore: Float!
  identifiedSkills: [String]
  identifiedKeywords: [String]
  summary: String
}

type Suggestion @table {
  analysisReport: AnalysisReport!
  suggestionText: String!
  category: String!
  relevanceScore: Float
}

type Comparison @table {
  user: User!
  comparisonDate: Timestamp!
  analysisReport1: AnalysisReport!
  analysisReport2: AnalysisReport!
}